networks:
  laravel:

volumes:
  postgresdb:
  mongodb:

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm
      - redis
      - mongo
      - postgres
    networks:
      - laravel
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - 'postgresdb:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - laravel

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    networks:
      - laravel
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - laravel
    restart: unless-stopped
    # If you need Redis authentication, uncomment the following:
    # command: redis-server --requirepass ${REDIS_PASSWORD}

  php-fpm:
    build: docker/php-fpm
    volumes:
      - './:/var/www/html'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - laravel
    restart: unless-stopped
